-- MySQL Script generated by MySQL Workbench
-- Sun Aug 13 12:38:45 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ispector
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ispector
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ispector` DEFAULT CHARACTER SET utf8 ;
USE `ispector` ;

-- -----------------------------------------------------
-- Table `ispector`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ispector`.`position` (
  `id` INT NOT NULL,
  `pos_decription` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ispector`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ispector`.`department` (
  `id` INT NOT NULL,
  `department_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ispector`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ispector`.`employee` (
  `id` INT NOT NULL,
  `emp_no` INT NULL,
  `emp_lname` VARCHAR(45) NULL,
  `emp_fname` VARCHAR(45) NULL,
  `emp_mname` VARCHAR(45) NULL,
  `DEPARTMENT_id` INT NOT NULL,
  `POSITION_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_EMPLOYEE_DEPARTMENT1`
    FOREIGN KEY (`DEPARTMENT_id`)
    REFERENCES `ispector`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLOYEE_POSITION1`
    FOREIGN KEY (`POSITION_id`)
    REFERENCES `ispector`.`position` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ispector`.`housekeeping_checklist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ispector`.`housekeeping_checklist` (
  `id` INT NOT NULL,
  `checklist_description` VARCHAR(45) NULL,
  `checklist_result` VARCHAR(45) NULL,
  `checklist_comments` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ispector`.`assessment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ispector`.`assessment` (
  `id` INT NOT NULL,
  `date_assessment_start` DATETIME NULL,
  `date_assessment_end` DATETIME NULL,
  `assessment_summary` VARCHAR(45) NULL,
  `assessment_recommendation` VARCHAR(45) NULL,
  `housekeepingsupervisor` INT NOT NULL,
  `housekeeping_staff` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ASSESSMENT_EMPLOYEE1`
    FOREIGN KEY (`housekeepingsupervisor`)
    REFERENCES `ispector`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ASSESSMENT_EMPLOYEE2`
    FOREIGN KEY (`housekeeping_staff`)
    REFERENCES `ispector`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ispector`.`workschedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ispector`.`workschedule` (
  `id` INT NOT NULL,
  `shift_name` VARCHAR(45) NULL,
  `shift_start_time` TIME(5) NULL,
  `shift_end_time` TIME(5) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ispector`.`room_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ispector`.`room_type` (
  `id` INT NOT NULL,
  `room_type` VARCHAR(45) NULL,
  `room_description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ispector`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ispector`.`room` (
  `id` INT NOT NULL,
  `room_no` VARCHAR(45) NULL,
  `ROOM_TYPE_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ROOM_ROOM_TYPE1`
    FOREIGN KEY (`ROOM_TYPE_id`)
    REFERENCES `ispector`.`room_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ispector`.`inspection_checklist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ispector`.`inspection_checklist` (
  `id` INT NOT NULL,
  `checklist_description` INT NOT NULL,
  `checklist_comments` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ispector`.`employee_cleans_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ispector`.`employee_cleans_room` (
  `id` INT NOT NULL,
  `ROOM_room_id` INT NOT NULL,
  `HOUSEKEEPING_CHECKLIST_id` INT NOT NULL,
  `INSPECTION_CHECKLIST_id` INT NOT NULL,
  `room_inspected` VARCHAR(1) NULL,
  `hkeeping_timein` TIMESTAMP(5) NULL,
  `hkeeping_timeout` TIMESTAMP(5) NULL,
  `inspection_timein` TIMESTAMP(5) NULL,
  `inspection_timeout` TIMESTAMP(5) NULL,
  `inspect_room` VARCHAR(45) NULL,
  `houkeepingsupervisor` INT NOT NULL,
  `housekeeping_staff` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_EMPLOYEE_has_ROOM_ROOM1`
    FOREIGN KEY (`ROOM_room_id`)
    REFERENCES `ispector`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLOYEE_CLEANS_ROOM_CHECKLIST1`
    FOREIGN KEY (`HOUSEKEEPING_CHECKLIST_id`)
    REFERENCES `ispector`.`housekeeping_checklist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLOYEE_CLEANS_ROOM_INSPECTION_CHECKLIST1`
    FOREIGN KEY (`INSPECTION_CHECKLIST_id`)
    REFERENCES `ispector`.`inspection_checklist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLOYEE_CLEANS_ROOM_EMPLOYEE1`
    FOREIGN KEY (`houkeepingsupervisor`)
    REFERENCES `ispector`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLOYEE_CLEANS_ROOM_EMPLOYEE2`
    FOREIGN KEY (`housekeeping_staff`)
    REFERENCES `ispector`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ispector`.`emloyee_has_workschedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ispector`.`emloyee_has_workschedule` (
  `EMPLOYEE_id` INT NOT NULL,
  `WORKSCHEDULE_id` INT NOT NULL,
  `time_in` DATETIME NULL,
  `time_out` DATETIME NULL,
  CONSTRAINT `fk_EMPLOYEE_has_WORKSCHEDULE_EMPLOYEE1`
    FOREIGN KEY (`EMPLOYEE_id`)
    REFERENCES `ispector`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLOYEE_has_WORKSCHEDULE_WORKSCHEDULE1`
    FOREIGN KEY (`WORKSCHEDULE_id`)
    REFERENCES `ispector`.`workschedule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
